[tools]
python = '3.13'
node = "latest"
bun = "latest"
uv = "latest"

[settings]
python.uv_venv_auto = true

[env]
_.python.venv = { path = ".venv", create = true }
S3_ACCESS_KEY_ID = ""
S3_SECRET_ACCESS_KEY = ""
S3_ENDPOINT_URL = ""
S3_REGION = "hel1"