[project]
name = "lean-reports"
version = "0.1.0"
description = "Generate reports from lean backruns"
requires-python = ">=3.13"
dependencies = [
    "basedpyright>=1.29.2",
    "boto3>=1.38.33",
    "datetime>=5.5",
    "pandas>=2.3.0",
    "plotly>=6.1.2",
    "streamlit>=1.45.1",
]
